name: Deploy Python app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install server dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip the server application files
      run: zip -r server.zip .

    - name: Print GitHub secrets
      run: |
        echo "Azure Web App Name: ${{ secrets.AZURE_WEBAPP_NAME }}"
        echo "Azure Web App Publish Profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./server.zip
